### ISSUE TITLE
After clicking the play button, the results section is filled with a red background

### ISSUE THREAD

**Issue by Ranada** [dotnet/try#1077]
#### Describe the bug
After clicking the play button for the examples under the 101-linq-samples page, the result sections are filled with a red background.

I see the following error message in the console.
```
tsMode.js:1 
        
        
POST https://localhost:50289/workspace/run?hostOrigin=https%3A%2F%2Flocalhost%3A50289%2Fdocs%2Frestrictions.md 500
(anonymous) @ tsMode.js:1
e.fetch @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
t.default @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
s @ tsMode.js:1
Promise.then (async)
u @ tsMode.js:1
(anonymous) @ tsMode.js:1
o @ tsMode.js:1
value @ tsMode.js:1
value @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
h @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
postMessage (async)
IFrameMessageBus.post @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
fulfilled @ trydotnet.min.js?v=1.0.20474.1:1
Promise.then (async)
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
__awaiter @ trydotnet.min.js?v=1.0.20474.1:1
executionService.run @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
fulfilled @ trydotnet.min.js?v=1.0.20474.1:1
Promise.then (async)
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
__awaiter @ trydotnet.min.js?v=1.0.20474.1:1
Session.run @ trydotnet.min.js?v=1.0.20474.1:1
runButton.onclick @ trydotnet.min.js?v=1.0.20474.1:1
tsMode.js:1 
        
        
POST https://localhost:50289/workspace/diagnostics?hostOrigin=https%3A%2F%2Flocalhost%3A50289%2Fdocs%2Frestrictions.md 500
(anonymous) @ tsMode.js:1
e.fetch @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
t.default @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
s @ tsMode.js:1
Promise.then (async)
u @ tsMode.js:1
(anonymous) @ tsMode.js:1
o @ tsMode.js:1
value @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
o @ tsMode.js:1
value @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
o @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
t.__tryOrUnsub @ tsMode.js:1
t.next @ tsMode.js:1
t._next @ tsMode.js:1
t.next @ tsMode.js:1
t._next @ tsMode.js:1
t.emitValue @ tsMode.js:1
t.notifyNext @ tsMode.js:1
t._next @ tsMode.js:1
t.next @ tsMode.js:1
ae @ tsMode.js:1
t._execute @ tsMode.js:1
t.execute @ tsMode.js:1
t.flush @ tsMode.js:1
setInterval (async)
t.requestAsyncId @ tsMode.js:1
t.schedule @ tsMode.js:1
e.schedule @ tsMode.js:1
t.schedule @ tsMode.js:1
(anonymous) @ tsMode.js:1
e._trySubscribe @ tsMode.js:1
e.subscribe @ tsMode.js:1
(anonymous) @ tsMode.js:1
r @ tsMode.js:1
t._tryNext @ tsMode.js:1
t._next @ tsMode.js:1
t.next @ tsMode.js:1
t.next @ tsMode.js:1
(anonymous) @ tsMode.js:1
value @ tsMode.js:1
Js @ tsMode.js:1
Xs @ tsMode.js:1
Ys @ tsMode.js:1
Gs @ tsMode.js:1
zs @ tsMode.js:1
bs @ tsMode.js:1
enqueueSetState @ tsMode.js:1
b.setState @ tsMode.js:1
s.onStateChange @ tsMode.js:1
v @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
dispatch @ tsMode.js:1
d @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
dispatch @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
dispatch @ tsMode.js:1
(anonymous) @ tsMode.js:1
w @ tsMode.js:1
(anonymous) @ tsMode.js:1
E.forEach.e.<computed> @ tsMode.js:1
(anonymous) @ tsMode.js:1
i @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
(anonymous) @ tsMode.js:1
postMessage (async)
IFrameMessageBus.post @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
fulfilled @ trydotnet.min.js?v=1.0.20474.1:1
Promise.then (async)
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
__awaiter @ trydotnet.min.js?v=1.0.20474.1:1
Session.setWorkspace @ trydotnet.min.js?v=1.0.20474.1:1
Session.setWorkspaceIfRequired @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
step @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
(anonymous) @ trydotnet.min.js?v=1.0.20474.1:1
__awaiter @ trydotnet.min.js?v=1.0.20474.1:1
Session.run @ trydotnet.min.js?v=1.0.20474.1:1
runButton.onclick @ trydotnet.min.js?v=1.0.20474.1:1
tsMode.js:1  Uncaught (in promise) Error
    at new t (tsMode.js:1:1)
    at e.<anonymous> (tsMode.js:1:1)
    at w (tsMode.js:1:1)
    at Generator._invoke (tsMode.js:1:1)
    at E.forEach.e.<computed> [as next] (tsMode.js:1:1)
    at s (tsMode.js:1:1)
```

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
![Screenshot 2023-06-06 210520](https://github.com/dotnet/try/assets/19520068/445ec2e1-602c-46fd-a0f7-575fad2babca)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge
    - [ ] Safari

**Comment by saintmenace04** [comment]
same problem here

**Comment by zebak007** [comment]
Same problem here ...

**Comment by Yzairi** [comment]
Same

**Comment by Wande-cole** [comment]
Same issue here. Has anyone been able to find a solution?

**Comment by xiaochen20034** [comment]
Same

**Comment by FaiyyazKhan** [comment]
Yes

**Comment by kalatchev** [comment]
The same
