### ISSUE TITLE
Ability to ignore or remove Console.ReadLine() and Console.ReadKey() with dotnet try

### ISSUE THREAD

**Issue by colbylwilliams** [dotnet/try#229]
### Summary
`Console.ReadLine()` or `Console.ReadKey()`  is found at the end of `static void Main(string[] args)` in almost all sample console apps found on GitHub (and elsewhere).  This is of course required (or at least preferred to provide a good experience) when executing these sample console apps on a local machine.

However, when executing the same sample apps with `dotnet try`, `Console.ReadLine()` prevents the execution from ever finishing and showing output, and `Console.ReadKey()` throws an exception:
```
Unhandled Exception: Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at SentimentAnalysisConsoleApp.Program.Main(String[] args)
```

Unfortunately, this is the only thing preventing us from making a majority of the sample apps in GitHub repos work with `dotnet try` by simply updating the README (and maybe refactoring some code).

### Example
[Here](https://github.com/dotnet/machinelearning-samples/commit/afded33fea2e9d0d876ffc437a0cbbd35dd1d363) is an example of where we ran into this issue after making the [sentiment analysis sample](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/BinaryClassification_SentimentAnalysis#try-it) work with `dotnet try`.

### Recommended Solutions
If we could make `dotnet try`, either:
1. Ignore `Console.ReadLine()` or `Console.ReadKey()` altogether possibly with the ability to opt-in with an argument, or
2. Add the ability to *remove* within a `#region` using arguments on the code-fence similar to the insert functionality provided by the `--destination-file` argument

It would be very simple to make any sample console app on GitHub work with with `dotnet try` by simply adding a few lines to the README.

**Comment by colbylwilliams** [comment]
cc: @CESARDELATORRE

**Comment by jonsequitur** [comment]
Thanks, @colbylwilliams. 

I opened #230 to describe an approach that might address this. Thoughts?

**Comment by colbylwilliams** [comment]
Thanks @jonsequitur.  Yes, I think the added functionality you outline in #230 would be a great addition to `dotnet try` and would address the issues I outlined.

I do still think the ability to _remove_ a `#region` (and the code within it) using arguments on the code-fence would be beneficial in multiple scenarios.  For example, being able to remove `#regions` and using the `--session` argument would greatly improve the ability to actually run smaller "chunks" of code.

It would also enhance a users ability to use the same console app code for samples, READMEs, documentation, websites, etc., by changing what is actually shown to the user for each scenario.  Including when `--editable false` is used.

While I agree that the enhancements you propose would allow me to solve the issue I outline above in a more robust way, being able to remove `#regions` would be a simple (likely easier to implement) solution, while the enhancements you propose a being worked on.

Plus I think there are enough useful use-cases for removing `#regions` that the feature would create long-term value and not be a short-term workaround.

_(All that said, I'm absolutely making assumptions on the effort required to add the remove-region functionality.  I may be way underestimating.)_
