### ISSUE TITLE
NuGet packages with native assets in a notebook

### ISSUE THREAD

**Issue by eerhardt** [dotnet/try#350]
#### Describe the bug
When using the [Microsoft.ML](https://www.nuget.org/packages/Microsoft.ML/) NuGet package in a notebook, you get an exception when ML.NET calls into a native assembly.

#### Repro

Run the following notebook:

```C#
#r "nuget:Microsoft.ML"
    
using Microsoft.ML;
using Microsoft.ML.Data;

class IrisData
{
    public IrisData(float sepalLength, float sepalWidth, float petalLength, float petalWidth)
    {
        SepalLength = sepalLength;
        SepalWidth = sepalWidth;
        PetalLength = petalLength;
        PetalWidth = petalWidth;
    }
    public float SepalLength;
    public float SepalWidth;
    public float PetalLength;
    public float PetalWidth;
}

var data = new []
{
    new IrisData(1.4f, 1.3f, 2.5f, 4.5f), 
    new IrisData(2.4f, 0.3f, 9.5f, 3.4f), 
    new IrisData(3.4f, 4.3f, 1.6f, 7.5f), 
    new IrisData(3.9f, 5.3f, 1.5f, 6.5f), 
};

MLContext mlContext = new MLContext();
var pipeline = mlContext.Transforms
    .Concatenate("Features", "SepalLength", "SepalWidth", "PetalLength", "PetalWidth")
    .Append(mlContext.Clustering.Trainers.KMeans("Features", numberOfClusters: 2));

try
{
    pipeline.Fit(mlContext.Data.LoadFromEnumerable(data));
}
catch (Exception e)
{
    Console.WriteLine(e);
}
```
This shouldn't throw an exception, but it does:

```
System.DllNotFoundException: Unable to load shared library 'CpuMathNative' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libCpuMathNative, 1): image not found
   at Microsoft.ML.Internal.CpuMath.Thunk.SumSqU(Single* ps, Int32 c)
   at Microsoft.ML.Internal.CpuMath.CpuMathUtils.SumSq(ReadOnlySpan`1 src)
   at Microsoft.ML.Numeric.VectorUtils.NormSquared(VBuffer`1& a)
   at Microsoft.ML.Trainers.KMeansBarBarInitialization.Initialize(IHost host, Int32 numThreads, IChannel ch, Factory cursorFactory, Int32 k, Int32 dimensionality, VBuffer`1[] centroids, Int64 accelMemBudgetMb, Int64& missingFeatureCount, Int64& totalTrainingInstances)
   at Microsoft.ML.Trainers.KMeansTrainer.TrainCore(IChannel ch, RoleMappedData data, Int32 dimensionality)
   at Microsoft.ML.Trainers.KMeansTrainer.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Submission#6.<<Initialize>>d__0.MoveNext()
```

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots

<img width="1030" alt="Screen Shot 2019-07-27 at 12 31 07 PM" src="https://user-images.githubusercontent.com/8291187/62084868-e065a980-b21f-11e9-83f8-988842d03837.png">

#### Please complete the following:
 - OS
    - [ ] Windows 10
    - [x] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by danmosemsft** [comment]
If it's possible to load 3.0 into the notebook, I assume that works around this (?)

**Comment by jonsequitur** [comment]
@eerhardt We fixed the example above, but I believe you had a slightly different repro for it.

**Comment by eerhardt** [comment]
Yes, try the same scenario with a different NuGet package that contains native assets, especially one that isn't as simple as `win`, `osx`, and `linux` assets.

Check out https://www.nuget.org/packages/LibGit2Sharp

![image](https://user-images.githubusercontent.com/8291187/63979568-d1705200-ca7e-11e9-9394-e36fb310138e.png)

With the current code, the above package won't work on any Linux system.
