### ISSUE TITLE
Graph error when running Tensorflow Transfer Learning on .NET Kernel

### ISSUE THREAD

**Issue by aslotte** [dotnet/try#565]
#### Describe the bug
I'm attempting to to Transfer Learning using ML.NET on top of Tensorflow in a Jupyter Notebook running a C# Kernel. The same scenario works well in Visual Studio 2019.
However, when running it on the C# Kernel, I'm getting the following error:

```
Unhandled Exception
Current graph is not default graph. Default Graph Key: grap-key-462764/, Current Graph Key: grap-key-1/
   at Tensorflow.Graph.OperationByName(String operName)
   at Microsoft.ML.Transforms.ImageClassificationTransformer.AddTransferLearningLayer(String labelColumn, String scoreColumnName, Single learningRate, Int32 classCount)
   at Microsoft.ML.Transforms.ImageClassificationTransformer..ctor(IHostEnvironment env, Session session, String[] outputColumnNames, String[] inputColumnNames, String modelLocation, Nullable`1 addBatchDimensionInput, Int32 batchSize, String labelColumnName, String finalModelPrefix, Architecture arch, String scoreColumnName, String predictedLabelColumnName, Single learningRate, DataViewSchema inputSchema, Nullable`1 classCount, Boolean loadModel, String predictionTensorName, String softMaxTensorName, String jpegDataTensorName, String resizeTensorName, String[] labelAnnotations)
   at Microsoft.ML.Transforms.ImageClassificationTransformer..ctor(IHostEnvironment env, Options options, DnnModel tensorFlowModel, IDataView input)
   at Microsoft.ML.Transforms.ImageClassificationEstimator.Fit(IDataView input)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Submission#16.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [X] Other:

#### Screenshots
![image](https://user-images.githubusercontent.com/30201569/67638361-10255b80-f8ba-11e9-8741-20a3bee36015.png)

#### Please complete the following:
 - OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [X] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Could you add more complete repro information, including which version of ML.NET you're loading?

**Comment by aslotte** [comment]
@jonsequitur - I added you to a private repo with the notebook and the dataset. You'll find the dataset under src/image%20classification.ipynb. You should be able to run that notebook to see if you get the same error or not. Thanks!
