### ISSUE TITLE
`dotnet try` doesn't work, due to invalid ssl certificate

### ISSUE THREAD

**Issue by 8** [dotnet/try#648]
#### The Problem
When executing `dotnet try demo` the webserver is started and the browser is launched, but no website is shown because the connection is marked as not secure, due to it being server over https without a valid certificate.

What I tried to solve the problem:
1. Changing the url to http instead of https, which didn't work, because it seems that the server is not listening to http.

2. Executing `dotnet try --help` to find a commandline switch to change that behavior, but there is only a switch for the port and the `uri` parameter throws an exception when called with the uri where it should host. Taking a look at the exception, it seems to me that the parameter uri triggers a WebRequest - maybe it wants to retrieve a file instead of host the webserver with the `--uri` parameter?

What do I need to do to host that thing over http?

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
![image](https://user-images.githubusercontent.com/278500/68900605-7de3db00-0734-11ea-8896-55e3ae2e4b90.png)
![image](https://user-images.githubusercontent.com/278500/68900672-9a801300-0734-11ea-833b-142c4af18187.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Firefox
    - [ ] Edge
    - [ ] Safari

**Comment by colombod** [comment]
you can register development certificates by doing the following  `dotnet dev-certs https --trust`

**Comment by 8** [comment]
Thanks for the tip!

I wasn't aware of `dev-certs` tool!
The documentation that I found on the tool is rather meager (2 sentences!) https://github.com/aspnet/AspNetCore/blob/master/src/Tools/dotnet-dev-certs/README.md

So If I understand correctly, that tools creates an ssl certificate and stores it (when called with `-t`) in the certificate store.

I executed the command and was asked to trust a certificate, which I did.
```
dotnet dev-certs https -t
Trusting the HTTPS development certificate was requested. A confirmation prompt will be displayed if the certificate was not previously trusted. Click yes on the prompt to trust the certificate.
A valid HTTPS certificate is already present.
```

I restarted the dotnet try `dotnet try demo` but I still got the same error in firefox.

I've checked the certificate store and found a trusted certificate for localhost, so I double checked with chrome and interestingly it works there.

Now I have even more questions :)

How did `dotnet try` know which certificate to use?
How did you figure out that this command needs to be executed - what did I miss?
How can I get it working in all browsers?
Why is it using https at all - imho this introduces a lot of additional complexity and errors for securing a local connection?

Take care,
Martin

**Comment by colombod** [comment]
@8 You are raising good points indeed. We should look into making this smother and working for browsers. The dev certificate is something that needs to be done with new version of CLI so keep this command at hand because you will need it in the future for web local development.

Let us see what can be done to alleviate the issues with try dot net !!!

**Comment by 8** [comment]
@colombod Interesting, I do dotnet core web development everyday and never used or needed it - I wasn't even aware of it.
So thanks for the pointer!

I am not aware of any local server tool requiring self-signed certs neither in dotnet nor in node. I don't understand what the benefits are - maybe somebody from the dev team can shed some light on this decision?

Thanks to your help, I can use the tool, but I would argue the issue still persists.
If you disagree feel free to close the issue :)

Take care,
Martin

**Comment by colombod** [comment]
Hi, we are looking into this issue.

**Comment by anitconsultantllc** [comment]
Got a similar issue today detailed by @8.  I actually got a "System.InvalidOperationException" due to not having a trusted self-signed cert but I actually had many certs for "localhost" already on my Windows 10 Enterprise machine (10+ or more).  I resolved this by doing the following:

1. Cleaning up ONLY the "localhost" certs in my certificate manager by going to...
![image](https://user-images.githubusercontent.com/6926175/72210077-94c85480-347b-11ea-93f7-6b8608e1068e.png)

![image](https://user-images.githubusercontent.com/6926175/72210100-c9d4a700-347b-11ea-9dc0-75f7ab4c714b.png)

and removing all the "localhost" certificates.
2. Generate the certificate:
          `dotnet dev-certs https`
3. Trust the certificate:
          `dotnet dev-certs https -t`
4. Run "dotnet try demo" again from an Administrativor Developer Command Prompt for 2019 and it started right up in Chrome Version 79.0.3945.117 (Official Build) (64-bit) with no issues.

####---------------------- My Console Output    ----------------------------------####
`D:\repos\try-samples\csharp8>dotnet try
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action`1 configureOptions)
   at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IServerAddressesFeature addresses, KestrelServerOptions serverOptions, ILogger logger, Func`2 createBinding)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServer.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at MLS.Agent.CommandLine.CommandLineParser.<>c.<Create>b__6_0(StartupOptions startupOptions, InvocationContext invocationContext) in F:\workspace\_work\1\s\MLS.Agent\CommandLine\CommandLineParser.cs:line 72
   at MLS.Agent.CommandLine.CommandLineParser.<>c__DisplayClass6_0.<Create>b__16(InvocationContext context, StartupOptions options) in F:\workspace\_work\1\s\MLS.Agent\CommandLine\CommandLineParser.cs:line 256
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at MLS.Agent.CommandLine.CommandLineParser.<>c__DisplayClass6_0.<<Create>b__5>d.MoveNext() in F:\workspace\_work\1\s\MLS.Agent\CommandLine\CommandLineParser.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass4_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__23_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext()

D:\repos\try-samples\csharp8>dotnet dev-certs https
The HTTPS developer certificate was generated successfully.

D:\repos\try-samples\csharp8>dotnet dev-certs https -t
Trusting the HTTPS development certificate was requested. A confirmation prompt will be displayed if the certificate was not previously trusted. Click yes on the prompt to trust the certificate.
A valid HTTPS certificate is already present.

D:\dotnettry>dotnet try demo
Hosting environment: Production
Content root path: C:\Users\Owner\.dotnet\tools\.store\dotnet-try\1.0.19620.2\dotnet-try\1.0.19620.2\tools\netcoreapp3.0\any
Now listening on: https://localhost:54978
Application started. Press Ctrl+C to shut down.`
