### ISSUE TITLE
Unable to use Tensors in Jupyter notebook due to loading errors

### ISSUE THREAD

**Issue by dasMulli** [dotnet/try#742]
#### Describe the bug

I'm currently trying to use the Jupyter kernel with ML.NET and the OnnxRuntime to prototype model inference based on pre-computed onnx models.
However I am unable to use System.Numerics.Tensors to create inputs to the model:

(EDIT - updated to minimal repro)
```csharp
#r "nuget:Microsoft.ML.OnnxRuntime,1.1.0"

using System.Numerics.Tensors;
var inputValues = new[]{12f, 10f, 17f, 5f};
var tInput = new DenseTensor<float>(inputValues.AsMemory(), new ReadOnlySpan<int>(new[]{4}));
```

errors with:
```
Unhandled Exception
Could not load file or assembly 'System.Numerics.Tensors, Version=0.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
   at Submission#23.<<Initialize>>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Submission#23.<Initialize>()
   at Submission#23.<Factory>(Object[] submissionArray)
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

This apperently tries to load a reference assembly into the runtime.
/cc @eerhardt 

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [x] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [x] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [x] Edge (Dev Channel)
    - [ ] Safari

**Comment by jonsequitur** [comment]
Which version of dotnet-try or dotnet-interactive are you using?

**Comment by KevinRansom** [comment]
Looking at this now:

Using a build from the latest master branch I get this output:

````
(4,49): error CS0121: The call is ambiguous between the following methods or properties: 'System.MemoryExtensions.AsMemory<T>(T[]?)' and 'System.MemoryExtensions.AsMemory<T>(T[]?)'
(4,61): error CS1503: Argument 2: cannot convert from 'System.ReadOnlySpan<int>' to 'bool'
(5,24): error CS0103: The name 'NamedOnnxValue' does not exist in the current context
````

Kevin

**Comment by KevinRansom** [comment]
Interestingly the F# version:
````
#r "nuget:Microsoft.ML,1.4.0"
#r "nuget:Microsoft.ML.OnnxTransformer,1.4.0"

open System.Numerics.Tensors
let inputValues = [| 12.0; 10.0; 17.0; 5.0 |]
let tInput = new DenseTensor<float>(inputValues.AsMemory(), new ReadOnlySpan<int>([|4|]))
let onnxInputs = [|NamedOnnxValue.CreateFromTensor<float>("float_input", tInput)|]
```

produces this:
````
input.fsx (7,20)-(7,34) typecheck error The value, namespace, type or module 'NamedOnnxValue' is not defined. Maybe you want one of the following:
   nameof
````

Which is exactly the same as is produced by the C# compiler output when built from a project:
````Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'NamedOnnxValue' does not exist in the current context	TensorRepro	C:\Users\kevinr\source\repos\TensorRepro\TensorRepro\Program.cs	12	Active


````

**Comment by dasMulli** [comment]
updated to repro to be more minimal and actually work (forgot to remove the last line and additional NuGet packages).

Used the current version on NuGet - `1.0.19553.4+001b36724d769e844a53b22e3833a23caed3dc68`

**Comment by jonsequitur** [comment]
@dasMulli The version on nuget.org is a bit out of date and a number of package fixes have been made since. Could you try installing dotnet-interactive per [these instructions](https://github.com/dotnet/try/blob/master/NotebooksLocalExperience.md) and see if you get a better result?

**Comment by dasMulli** [comment]
Nice, any chance of adding pointers to this doc to the previously published blog post instructions for using Jupiter notebooks for .net? (Google foo..)

So the dotnet-try version has issues using S.N.Tensors at all.

dotnet-interactive version cannot create a DenseTensor when using the System.Numerics.Tensors 0.1.0 NuGet package, but the 0.2.0 previews work fine.
This version also seems to pick a version of `NamedOnnxValue.CreateFromTensor` that actually uses the tensors implementation shipped in OnnxRuntime (Microsoft.ML.OnnxRuntime.Tensors) as a replacement for the System.Numerics ones. (it gets more interesting b/c the published Microsoft.ML.OnnxTransformer don't work with current OnnxRuntime packages but that's a different story..)

**Comment by jonsequitur** [comment]
There'll be a more general announcement soon.

**Comment by KevinRansom** [comment]
Master branch fails with these errors:
````
(2,23): error CS0234: The type or namespace name 'Tensors' does not exist in the namespace 'System.Numerics' (are you missing an assembly reference?)
(4,18): error CS0246: The type or namespace name 'DenseTensor<>' could not be found (are you missing a using directive or an assembly reference?)
(4,49): error CS0121: The call is ambiguous between the following methods or properties: 'System.MemoryExtensions.AsMemory<T>(T[]?)' and 'System.MemoryExtensions.AsMemory<T>(T[]?)'
````

The equivalent C# project works great, So I will look at why:
````
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxTransformer" Version="1.4.0" />
  </ItemGroup>
</Project>
````

````
using System;

using System.Numerics.Tensors;

namespace TensorRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var inputValues = new[] { 12f, 10f, 17f, 5f };
            var tInput = new DenseTensor<float>(inputValues.AsMemory(), new ReadOnlySpan<int>(new[] { 4 }));
        }
    }
}

````

**Comment by eerhardt** [comment]
> I'm currently trying to use the Jupyter kernel with ML.NET and the OnnxRuntime to prototype model inference based on pre-computed onnx models.

Note that the `1.0.0`+ versions of the [Microsoft.ML.OnnxRuntime](https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime) package don't reference `System.Numerics.Tensors`. Instead, they have basically a copy of the System.Numerics.Tensors code in it. This was done because `Microsoft.ML.OnnxRuntime` wanted to ship a stable version of their API (i.e. `1.0.0`) and couldn't take a dependency on an unstable package - System.Numerics.Tensors is still at `0.1.0`.

Also note that `1.4.0` of ML.NET is not compatible with the `1.0.0`+ versions of the `Microsoft.ML.OnnxRuntime`. It still uses `0.5.1` (see the Dependencies under https://www.nuget.org/packages/Microsoft.ML.OnnxTransformer/1.4.0). You would need to use the `1.5.0-preview` of ML.NET in order to use the `1.0.0`+ versions of `Microsoft.ML.OnnxRuntime`.

**Comment by dasMulli** [comment]
Thanks, 1.5.0-preview seems to have all ends covered - then I ran into https://github.com/dotnet/machinelearning/issues/4646

I'm closing this since I don't see any immediate issues - although the loading bug seems weird, using newer 2.0 preview version of S.N.Tensors (without any onnx or MLnet) seems to work.

The issue that @KevinRansom extracted seems to be due to the namspace change between the system.numerics.tensors package and the fork that OnnxRuntime ships.

Thanks for all the help and directions.

**Comment by KevinRansom** [comment]
@dasMulli , hey mate, I'm using this issue to track the code-change.  So I would like to keep this open for now, if that is good with you :-)
