### ISSUE TITLE
Unhandled Exception on Jupyter Notebook installing Microsoft.Data.Analysis

### ISSUE THREAD

**Issue by qawnaoya** [dotnet/try#813]
#### Describe the bug

on Jupyter Notebook

#r "nuget:Microsoft.Data.Analysis, 0.2.0"

Installing package Microsoft.Data.Analysis, version 0.2.0...............done!
Unhandled Exception
Object reference not set to an instance of an object.
   at WorkspaceServer.Packaging.PackageRestoreContext.OutputPath()
   at WorkspaceServer.Kernel.CSharpKernelExtensions.<>c__DisplayClass2_1.<<UseNugetDirective>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.Commands.KernelCommandBase.InvokeAsync(KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelBase.HandleInternalAsync(IKernelCommand command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _)
   at Microsoft.DotNet.Interactive.KernelBase.<AddSetKernelMiddleware>b__8_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(IKernelCommand command, KernelInvocationContext context)

#### Did this error occur while using `dotnet try` or online?
- [ ] `dotnet-try`
- [ O] .NET Jupyter Notebook 
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Please complete the following:
 - OS
    - [ O] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ O] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Are you using `dotnet try` or `dotnet interactive`? 

If you're still using `dotnet-try` please update to the latest `dotnet-interactive`, run `dotnet interactive jupyter install` (from an Anaconda Prompt or terminal where jupyter is on the path), and see if that resolves the issue.
