### ISSUE TITLE
Unhandled Exception No design time or full build available

### ISSUE THREAD

**Issue by yduit** [dotnet/try#844]
#### Describe the bug
When installing any nuget package using for example: #r "nuget:Microsoft.Data.Analysis" using VS 2019 16.7.0 preview2.0

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ ] Other:

#### Screenshots
Installing package Microsoft.Data.Analysis......done!
Unhandled Exception
No design time or full build available
   at WorkspaceServer.Packaging.Package.CreateRoslynWorkspace()
   at WorkspaceServer.Packaging.Package.ProcessFullBuildRequest(Budget budget)
   at WorkspaceServer.Packaging.Package.<SetupWorkspaceCreationFromBuildChannel>b__54_0(Budget budget)
   at WorkspaceServer.Packaging.PackageRestoreContext.CreatePackage(String name)
   at WorkspaceServer.Packaging.PackageRestoreContext.AddPackage(String packageName, String packageVersion)
   at WorkspaceServer.Kernel.CSharpKernelExtensions.<>c__DisplayClass2_1.<<UseNugetDirective>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.Interactive.Commands.KernelCommandBase.InvokeAsync(KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelBase.HandleInternalAsync(IKernelCommand command, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _)
   at Microsoft.DotNet.Interactive.KernelBase.<AddSetKernelMiddleware>b__8_0(IKernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next)
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(IKernelCommand command, KernelInvocationContext context)
#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Safari

**Comment by adante111** [comment]
This also occurs for me. Some environment settings:

* Windows 10 Pro x64 10.0.18362.
* `python --version` returns `Python 3.7.7`
* JupyterNotebook and JupyterLab are installed via Anaconda Navigator (ages ago, and since upgraded via (I think?) `conda update conda`)
* JupyterLab 2.1.4 as shown from Help -> About and `jupyter --version`
* JupyterNobook says `The version of the notebook server is: 6.0.3` and `jupyter --version` reports `jupyter-notbook 6.0.3`
* `jupyter kernelspec list` reports:
   *     .net-csharp    C:\Users\adante\AppData\Roaming\jupyter\kernels\.net-csharp
         .net-fsharp    C:\Users\adante\AppData\Roaming\jupyter\kernels\.net-fsharp
         .rust           C:\Users\adante\AppData\Roaming\jupyter\kernels\rust
         .python3        C:\Users\adante\Anaconda3\share\jupyter\kernels\python3
* `dotnet --version` reports `3.1.300`
* `(dir (Get-Command dotnet).Path.Replace('dotnet.exe', 'sdk')).Name` in powershell (https://stackoverflow.com/questions/38567353/how-to-determine-if-net-core-is-installed) returns `3.1.300`
* `dotnet try --version` reports `1.0.19553.4+001b36724d769e844a53b22e3833a23caed3dc68`
* `dotnet --info` output is https://pastebin.com/pFr32KZm
* `conda --list output` is https://pastebin.com/LTnQMidU

**Comment by edirgarcia** [comment]
I observe the same thing.
for me it was working before, then I reinstalled/updated my .NET core SDK and it started happening.
I then tried to revert to a previous version of the SDK and it started working again.
Feel free to reach out internally at edirga if you want more detail.
But I can confirm this is an issue at the very least with SDK >3.1.300 

for @adante111, and @yduit try temporarily installing SDK 3.1.100, this seems to be working for me.

**Comment by yduit** [comment]
Thanks edirgarcia for the workaround and confirmation.
I was playing with Blazor webassembly along with ml.net. Older SDK version will not work for me.
