### ISSUE TITLE
Internal Error 500: Running any snippet will cause an error

### ISSUE THREAD

**Issue by zmjack** [dotnet/try#855]
#### Describe the bug
I used the command 'dotnet try --verbose' and the site started up.
But if I run any code snippets on the website, I get an error:

> [MLS.Agent.Middleware.ExceptionFilter]  ? System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.

#### Did this error occur while using `dotnet try` or online?
- [x] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [x] Other:

> 2020-07-08T08:24:01.7676428Z [|6143940c-482c8867e8e63d61.1.] [MLS.Agent.Middleware.ExceptionFilter]  ? System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
>    at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53

#### Screenshots
![image](https://user-images.githubusercontent.com/24598247/86896627-d3904c00-c138-11ea-9584-e76b27fc3d0a.png)
![image](https://user-images.githubusercontent.com/24598247/86897074-882a6d80-c139-11ea-9ef3-9140eaf357f4.png)

#### Please complete the following:
 - OS
    - [x] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [x] Chrome
    - [x] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Please try installing the latest version:

```console
> dotnet tool uninstall -g dotnet-try
> dotnet tool install -g Microsoft.dotnet-try
```

**Comment by zmjack** [comment]
Unfortunately, I installed the Microsoft.dotnet-try 1.0.20268.1, but the error has not disappeared.

2020-07-08T15:45:03.4488876Z [MLS.Agent.Middleware.ExceptionFilter]  ❌ System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---

**Comment by colombod** [comment]
@zmjack we have a newest version not yet published on nuget.org
could you see if upgrading using the following command addresses the issues you are encountering

```
dotnet tool update -g --add-source "https://dotnet.myget.org/F/dotnet-try/api/v3/index.json" Microsoft.dotnet-try
```

**Comment by zmjack** [comment]
@colombod  Thanks!
I tried the newer version and it's working now.

But I think it still has some bugs.

Please look at the GIF:
![Honeycam 2020-07-09 15-54-25](https://user-images.githubusercontent.com/24598247/87013196-d94f6580-c1fc-11ea-944e-40254ac92794.gif)

When I run a snippet, a red block will be displayed if the file 'package_fullBuild.binlog' is not in the directory (./snippets).
Wait until the file is generated and everything is fine.

**Comment by colombod** [comment]
Looks like a race condition on first build action

**Comment by colombod** [comment]
> @colombod Thanks!
> I tried the newer version and it's working now.
> 
> But I think it still has some bugs.
> 
> Please look at the GIF:
> ![Honeycam 2020-07-09 15-54-25](https://user-images.githubusercontent.com/24598247/87013196-d94f6580-c1fc-11ea-944e-40254ac92794.gif)
> 
> When I run a snippet, a red block will be displayed if the file 'package_fullBuild.binlog' is not in the directory (./snippets).
> Wait until the file is generated and everything is fine.

Looks like that the binlog generation is in flight when you attempt the first run.  Looks like a race condition to address
