### ISSUE TITLE
dotnet try --verbose throws logging exception

### ISSUE THREAD

**Issue by gwgrubbs** [dotnet/try#881]
#### Describe the bug
Running "dotnet try --verbose"  produces exception shortly after start.

#### Did this error occur while using `dotnet try` or online?
- [X ] `dotnet-try`
- [ ] online

#### What kind of error was it?
- [ ] User Interface (UI):  For example the output never displayed 
- [ ] Service Error: For example "The service is temporarily unavailable. We are working on it"
- [ X] Other:

#### Screenshots
Log output (until exception occurs):

2020-09-30T20:47:26.3944332Z [MLS.Agent.Program]  ⏱ No Key Provided
2020-09-30T20:47:26.4752622Z [|54dd7ec3-4d023a1191ab3891.] [MLS.Agent.Startup] [ConfigureServices]  ▶
2020-09-30T20:47:26.5293590Z [|54dd7ec3-4d023a1191ab3891.] [MLS.Agent.Startup] [ConfigureServices]  ⏹ -> ✔ (54.2216ms)
2020-09-30T20:47:26.5508496Z [|54dd7ec3-4d023a1191ab3891.] [WorkspaceServer.Packaging.Package]  ℹ Packages path is C:\Users\xxx\.trydotnet\packages
2020-09-30T20:47:26.5717618Z [|54dd7ec3-4d023a1191ab3891.1.] [MLS.Agent.Startup] [Configure]  ▶
2020-09-30T20:47:26.6616454Z [|54dd7ec3-4d023a1191ab3891.1.] [MLS.Agent.Startup] [Configure]  ⏹ -> ✔ (89.9272ms)
Hosting environment: Production
Content root path: C:\Users\xxx\.dotnet\tools\.store\dotnet-try\1.0.19553.4\dotnet-try\1.0.19553.4\tools\netcoreapp3.0\any
Now listening on: https://localhost:54637
Application started. Press Ctrl+C to shut down.
2020-09-30T20:47:32.4576232Z [|54dd7ec4-4d023a1191ab3891.] [MLS.Agent.Controllers.ClientConfigurationController] [ConfigurationAsync]  ⏹ -> ✔ (40.1516ms)
2020-09-30T20:47:33.6264037Z [|54dd7ec5-4d023a1191ab3891.] [MLS.Agent.Controllers.LanguageServicesController] [Diagnostics]  ▶
2020-09-30T20:47:33.6270429Z [|54dd7ec5-4d023a1191ab3891.] [MLS.Agent.Controllers.LanguageServicesController] [Diagnostics]  ℹ (0.7193ms) Processing workspaceType D:\src\db-ex\samples\mssql\Console\Console.csproj
2020-09-30T20:47:33.7963504Z [|54dd7ec5-4d023a1191ab3891.] [MLS.Agent.Controllers.LanguageServicesController] [Diagnostics]  ⏹ -> ❌ (170.028ms)

Exception output:

2020-09-30T20:43:03.5817700Z [MLS.Agent.Middleware.ExceptionFilter]  ❌ System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog()
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget)
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget)
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at MLS.Agent.Controllers.LanguageServicesController.Diagnostics(WorkspaceRequest request, String timeoutInMilliseconds) in F:\workspace\_work\1\s\MLS.Agent\Controllers\LanguageServicesController.cs:line 131
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog()
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget)
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget)
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at MLS.Agent.Controllers.LanguageServicesController.Diagnostics(WorkspaceRequest request, String timeoutInMilliseconds) in F:\workspace\_work\1\s\MLS.Agent\Controllers\LanguageServicesController.cs:line 131
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-30T20:43:24.7081427Z [|6eda3de6-445854a959bb6441.] [MLS.Agent.Controllers.RunController] [Run]  ▶
2020-09-30T20:43:24.7089085Z [|6eda3de6-445854a959bb6441.] [MLS.Agent.Controllers.RunController] [Run]  ℹ (0.8378ms) Processing workspaceType D:\src\db-ex\samples\mssql\Console\Console.csproj
2020-09-30T20:43:24.7143853Z [|6eda3de6-445854a959bb6441.1.] [WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer] [Run]  ▶
2020-09-30T20:43:24.7209819Z [|6eda3de6-445854a959bb6441.1.] [WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer] [Run]  ⏹ (6.6794ms)
2020-09-30T20:43:24.7219258Z [|6eda3de6-445854a959bb6441.] [MLS.Agent.Controllers.RunController] [Run]  ⏹ -> ❌ (13.8549ms)
2020-09-30T20:43:24.7229013Z [MLS.Agent.Middleware.ExceptionFilter]  ❌ System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog()
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget)
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget)
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.Run(WorkspaceRequest request, Budget budget)
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.Run(WorkspaceRequest request, Budget budget)
   at MLS.Agent.Controllers.RunController.Run(WorkspaceRequest request, String timeoutInMilliseconds) in F:\workspace\_work\1\s\MLS.Agent\Controllers\RunController.cs:line 75
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog()
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget)
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget)
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.Run(WorkspaceRequest request, Budget budget)
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.Run(WorkspaceRequest request, Budget budget)
   at MLS.Agent.Controllers.RunController.Run(WorkspaceRequest request, String timeoutInMilliseconds) in F:\workspace\_work\1\s\MLS.Agent\Controllers\RunController.cs:line 75
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2020-09-30T20:43:25.6917730Z [|6eda3de7-445854a959bb6441.] [MLS.Agent.Controllers.LanguageServicesController] [Diagnostics]  ▶
2020-09-30T20:43:25.6926820Z [|6eda3de7-445854a959bb6441.] [MLS.Agent.Controllers.LanguageServicesController] [Diagnostics]  ℹ (0.9504ms) Processing workspaceType D:\src\db-ex\samples\mssql\Console\Console.csproj
2020-09-30T20:43:25.6953845Z [|6eda3de7-445854a959bb6441.] [MLS.Agent.Controllers.LanguageServicesController] [Diagnostics]  ⏹ -> ❌ (3.6527ms)
2020-09-30T20:43:25.6962728Z [MLS.Agent.Middleware.ExceptionFilter]  ❌ System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog()
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget)
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget)
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at MLS.Agent.Controllers.LanguageServicesController.Diagnostics(WorkspaceRequest request, String timeoutInMilliseconds) in F:\workspace\_work\1\s\MLS.Agent\Controllers\LanguageServicesController.cs:line 131
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) System.AggregateException: One or more errors occurred. (Unsupported log file format. Latest supported version is 7, the log file has version 9.)
 ---> System.NotSupportedException: Unsupported log file format. Latest supported version is 7, the log file has version 9.
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(Stream stream) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 53
   at Microsoft.Build.Logging.StructuredLogger.BinLogReader.Replay(String sourceFilePath) in C:\MSBuildStructuredLog\src\StructuredLogger\BinaryLogger\BinLogReader.cs:line 37
   at Buildalyzer.AnalyzerManager.Analyze(String binLogPath, IEnumerable`1 buildLoggers)
   at WorkspaceServer.Packaging.Package.LoadDesignTimeBuildFromBuildLogFile(Package package, FileSystemInfo binLog)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at WorkspaceServer.Packaging.Package.TryLoadDesignTimeBuildFromBuildLog()
   at WorkspaceServer.Packaging.Package..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.RebuildablePackage..ctor(String name, IPackageInitializer initializer, DirectoryInfo directory, IScheduler buildThrottleScheduler)
   at WorkspaceServer.Packaging.PackageBuilder.GetPackage(Budget budget)
   at WorkspaceServer.PackageRegistry.<>c__DisplayClass10_0.<<GetPackageFromPackageBuilder>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at WorkspaceServer.PackageRegistry.Get[T](String packageName, Budget budget)
   at WorkspaceServer.Servers.Roslyn.RoslynWorkspaceServer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at WorkspaceServer.Servers.WorkspaceServerMultiplexer.GetDiagnostics(WorkspaceRequest request, Budget budget)
   at MLS.Agent.Controllers.LanguageServicesController.Diagnostics(WorkspaceRequest request, String timeoutInMilliseconds) in F:\workspace\_work\1\s\MLS.Agent\Controllers\LanguageServicesController.cs:line 131
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

#### Please complete the following:
 - OS
    - [X ] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ X] Edge
    - [ ] Safari

**Comment by jonsequitur** [comment]
Could you provide the output from `dotnet try --version` and `dotnet --info`?

**Comment by gwgrubbs** [comment]
```dotnet try --version```: 
1.0.19553.4+001b36724d769e844a53b22e3833a23caed3dc68

```dotnet --info```:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jonsequitur** [comment]
You're using the deprecated version of `dotnet-try`. Try uninstalling it and installing the new version:

```console
> dotnet tool uninstall -g dotnet-try
> dotnet tool install -g Microsoft.dotnet-try
```

**Comment by jonsequitur** [comment]
If this didn't solve the issue please reopen.
