### ISSUE TITLE
Code with two Main methods causes an exception

### ISSUE THREAD

**Issue by svick** [dotnet/try#91]
I tried to run the following code using try.dot.net:

```c#
class Program
{
  static void Main() {}
}
class Program2
{
  static void Main() {}
}
```

When I did, I got the following exception:

```
Unhandled Exception: System.InvalidOperationException: Sequence contains more than one element
 at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
 at WorkspaceServer.Servers.Scripting.ScriptingWorkspaceServer.<EmulateConsoleMainInvocation>d__13.MoveNext() in /app/WorkspaceServer/Servers/Scripting/ScriptingWorkspaceServer.cs:line 429
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at WorkspaceServer.Servers.Scripting.ScriptingWorkspaceServer.<Run>d__3.MoveNext() in /app/WorkspaceServer/Servers/Scripting/ScriptingWorkspaceServer.cs:line 260
```

It's probably okay that this produces an error, but I think the error should be more friendly.

**Comment by jonsequitur** [comment]
This is an artifact of a special case we have in place for script-based code snippets.

If you try this in a full C# workspace (e.g. https://try.dot.net/?workspaceType=console), you'll see the correct exception:

```
(3,15): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point.
```
